export const projects = [
  {
    id: 1,
    title: "Vortex_Engine",
    description: "Descrição do projeto 1",
    image: "/background_01.svg",
    modulo: "Módulo 1",
    status: "Concluído",
    stacks: ["React", "TypeScript"],
    version: "v1.0",
  },
  {
    id: 2,
    title: "Titan_DB",
    description: "Descrição do projeto 2",
    image: "/background_02.svg",
    modulo: "Módulo 2",
    status: "Em Andamento",
    stacks: ["Vue.js", "JavaScript"],
    version: "v1.0",
  },
  {
    id: 3,
    title: "Pulse_Net",
    description: "Descrição do projeto 3",
    image: "/background_03.svg",
    modulo: "Módulo 3",
    status: "Pendente",
    stacks: ["Angular", "Python"],
    version: "v1.0",
  },
  {
    id: 4,
    title: "Shadow_OS",
    description: "Descrição do projeto 4",
    image: "/background_04.svg",
    modulo: "Módulo 4",
    status: "Em Desenvolvimento",
    stacks: ["React", "Node.js"],
    version: "v1.0",
  },
];